import test from 'node:test';
import assert from 'node:assert/strict';

import { NextRequest } from 'next/server.js';

import { POST, buildCompactSitePrompt, extractSafeHtml } from '../app/api/build-site/route.ts';

test('extractSafeHtml keeps a complete page and injects an isolated content policy', () => {
  const html = extractSafeHtml(`\`\`\`html
<!doctype html><html lang="pt-BR"><head><title>Teste</title></head><body><main>Conteúdo</main></body></html>
\`\`\``);

  assert.match(html, /<!doctype html>/i);
  assert.match(html, /Content-Security-Policy/);
  assert.match(html, /connect-src 'none'/);
});

test('extractSafeHtml removes external executable embeds', () => {
  const html = extractSafeHtml('<!doctype html><html><head></head><body><iframe src="https://example.com"></iframe><script src="https://example.com/a.js"></script><main>Seguro</main></body></html>');

  assert.doesNotMatch(html, /iframe/i);
  assert.doesNotMatch(html, /script src/i);
  assert.match(html, /<main>Seguro<\/main>/);
});

test('extractSafeHtml rejects responses that are not complete pages', () => {
  assert.equal(extractSafeHtml('<section>Somente um fragmento</section>'), '');
});

test('buildCompactSitePrompt requires verified data and a complete standalone page', () => {
  const prompt = buildCompactSitePrompt('NEGÓCIO: exemplo verificado');

  assert.match(prompt, /<!doctype html>/i);
  assert.match(prompt, /Não invente telefone/i);
  assert.match(prompt, /não use bibliotecas/i);
  assert.match(prompt, /NEGÓCIO: exemplo verificado/);
});

test('POST does not apply a shared anonymous click limit when no private provider key exists', async () => {
  const previousOpenAI = process.env.OPENAI_API_KEY;
  const previousKimi = process.env.MOONSHOT_API_KEY;
  delete process.env.OPENAI_API_KEY;
  delete process.env.MOONSHOT_API_KEY;
  try {
    for (let attempt = 0; attempt < 8; attempt += 1) {
      const request = new NextRequest('http://localhost:3000/api/build-site', {
        method: 'POST',
        headers: { Origin: 'http://localhost:3000', 'Content-Type': 'application/json' },
        body: JSON.stringify({ action: 'build', provider: 'auto', prompt: 'Brief verificado. '.repeat(40) }),
      });
      const response = await POST(request);
      const payload = await response.json() as { code?: string };
      assert.equal(response.status, 503);
      assert.equal(payload.code, 'provider_not_configured');
    }
  } finally {
    if (previousOpenAI === undefined) delete process.env.OPENAI_API_KEY;
    else process.env.OPENAI_API_KEY = previousOpenAI;
    if (previousKimi === undefined) delete process.env.MOONSHOT_API_KEY;
    else process.env.MOONSHOT_API_KEY = previousKimi;
  }
});

test('POST validates HTML generated by the browser AI without requiring a private provider key', async () => {
  const request = new NextRequest('http://localhost:3000/api/build-site', {
    method: 'POST',
    headers: { Origin: 'http://localhost:3000', 'Content-Type': 'application/json' },
    body: JSON.stringify({
      action: 'sanitize',
      model: 'claude-sonnet-4-6',
      rawContent: '<!doctype html><html><head><title>Site</title></head><body><main>Gerado pela IA</main></body></html>',
    }),
  });
  const response = await POST(request);
  const payload = await response.json() as { provider?: string; model?: string; html?: string };

  assert.equal(response.status, 200);
  assert.equal(payload.provider, 'puter');
  assert.equal(payload.model, 'claude-sonnet-4-6');
  assert.match(payload.html ?? '', /Content-Security-Policy/);
  assert.match(payload.html ?? '', /Gerado pela IA/);
});
